// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#include <openenclave/host.h>
#include <stdio.h>
#include <stdlib.h>


// Include the untrusted guessing header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the guessing.edl file.
#include "guessing_u.h"

//The global play variable determine if we guessed the value we end the loop
bool play = true;
 
bool check_simulate_opt(int* argc, const char* argv[])
{
    for (int i = 0; i < *argc; i++)
    {
        if (strcmp(argv[i], "--simulate") == 0)
        {
            fprintf(stdout, "Running in simulation mode\n");
            memmove(&argv[i], &argv[i + 1], (*argc - i) * sizeof(char*));
            (*argc)--;
            return true;
        }
    }
    return false;
}

//This function print the max value entered by the user
void host_guessing_init(int max) {
   
    fprintf(stdout, "Max value : %d \n", max);
}

//This function print the result 
void host_guessing_result(int value) {
   
    if(value == 0){
        fprintf(stdout, "Wrong guess\n");
        play = true;
    }else{
        fprintf(stdout, "You Won\n");
        play = false;
    }
}

int main(int argc, const char* argv[])
{
    oe_result_t result;
    int ret = 1;
    oe_enclave_t* enclave = NULL;
    int user_input;
    int max_guess = 5; // The maximum number of tries
    int turn = 0;

    uint32_t flags = OE_ENCLAVE_FLAG_DEBUG;
    if (check_simulate_opt(&argc, argv))
    {
        flags |= OE_ENCLAVE_FLAG_SIMULATE;
    }

    if (argc != 2)
    {
        fprintf(
            stderr, "Usage: %s enclave_image_path [ --simulate  ]\n", argv[0]);
        goto exit;
    }

    // Create the guessing enclave
    result = oe_create_guessing_enclave(
        argv[1], OE_ENCLAVE_TYPE_AUTO, flags, NULL, 0, &enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "oe_create_guessing_enclave(): result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

     // Call into the enclave_helloworld function
    result = enclave_helloworld(enclave);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into enclave_helloworld failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }


    //Calling the guessing_init_enclave function
    user_input = 0;
    printf("Your input : ");
    scanf("%d", &user_input);
    result = enclave_guessing_init(enclave, user_input);
    if (result != OE_OK)
    {
        fprintf(
            stderr,
            "calling into guessing_init_enclave failed: result=%u (%s)\n",
            result,
            oe_result_str(result));
        goto exit;
    }

    //Loop
    do{
        printf("\nEnter a guess value :  ");
        //Calling the enclave_guessing_send function
        user_input = 0;
        scanf("%d", &user_input);
        printf("\nYou Entered :  %d \n", user_input);
        result = enclave_guessing_send(enclave, user_input);
        if (result != OE_OK)
        {
            fprintf(
                stderr,
                "calling into enclave_guessing_send failed: result=%u (%s)\n",
                result,
                oe_result_str(result));
            goto exit;
        }
        turn++;
    }while(play && turn <= max_guess);

    if (turn > max_guess)
    {
        printf("\nNumber of trials exceeded.\n");
    }
    
    ret = 0;
    exit:
    // Clean up the enclave if we created one
    if (enclave)
        oe_terminate_enclave(enclave);

    return ret;
}
